### ISSUE TITLE
Request for iOS 11.3.1 (15E302)

### ISSUE THREAD

**Issue by HasnAr** [filsv/iPhoneOSDeviceSupport#10]

**Comment by winnypina** [comment]
hey @HasnAr 
https://github.com/filsv/iPhoneOSDeviceSupport/issues/7

is working for me.

**Comment by HariNarayanan777** [comment]
i am also need this. as of now please. 11.3.1 (15E302)...!

**Comment by HasnAr** [comment]
hey back @winnypina 
#7 
works for you cause you didn't update to 11.3.1

**Comment by mdabutaleb** [comment]
Anyone got this solution? I still need 11.3.1 (15E302). If anyone have please let me know.

**Comment by guitarrapc** [comment]
Any update with?

**Comment by mdabutaleb** [comment]
See this ans: https://stackoverflow.com/a/51733058/4934273 
I got the solution from here.

**Comment by arivanandan** [comment]
Download the file mentioned in #7 

Rename the folder to `11.3.1`.

**Comment by filsv** [comment]
Guys you also can use iOS 12 support files which probably will fix your issue, if not - let me now I'll upload iOS 11.3.1 here.

**Comment by filsv** [comment]
@HasnAr  hi, you can use [11.4 (15F5037c)](https://github.com/filsv/iPhoneOSDeviceSupport/tree/master/11.4%20(15F5037c)) instead.
