### ISSUE TITLE
14.8 device support files are missing

### ISSUE THREAD

**Issue by zjupure** [filsv/iPhoneOSDeviceSupport#100]
please add support for 14.8
![image](https://user-images.githubusercontent.com/5836221/133405342-766cf883-2039-4d8d-9c88-f24905564b49.png)

**Comment by knewk** [comment]
Yes please, it would be great, to get 14.8

**Comment by knewk** [comment]
I just build a project to my iphone running 14.8 from xcode 12.4 running on Catalina 10.15.7 by copying the 14.7.1 device support files here [https://github.com/filsv/iPhoneOSDeviceSupport/blob/master/14.7.1.zip] into a folder called 14.8 under the xcode usual device support directory.

**Comment by mendaparadarshit** [comment]
Yes please today I have just upgrade my device to 14.8 and its not working. can anyone upload it please!

**Comment by knewk** [comment]
See above for workaround.

**Comment by livazz** [comment]
I renamed 14.7.1 to 14.8 and it worked.

**Comment by jasonbrowne44** [comment]
For me, renaming 14.7.1 to 14.8 worked, but I had to set all the file permissions on the 14.8 files to 777 using "sudo chmod 777 *" on the 14.8 top directory and the files in the directories.  It initially complained that it didn't have permission to see the 14.8 files.  It also failed a few times and then finally worked.
