### ISSUE TITLE
15.0 is not supporting

### ISSUE THREAD

**Issue by 01234abhishek** [filsv/iPhoneOSDeviceSupport#101]
I have downloaded 15.0 and paste in the Xcode components. I am using 12.4 version. my iPhone iOS version is 15.0. so I paste 15.0 folder but it is showing code signature version is no longer supported. Need help regarding this.

**Comment by barisyild** [comment]
I think there are 2 solutions available:

1- Downgrading iOS Device to 14.x version.
2- Updating the XCode software to the latest version. (Xcode 13)

**Comment by kubajakowski** [comment]
AFAIK code signature wsa shown when we were trying to build and run on macOS Catalina. On BigSur everything started to build without errors. 
I can confirm that after adding support files I'm able to run my app on iOS 15 built on Big Sur on Xcode 12.4.

**Comment by filsv** [comment]
@01234abhishek You can try to use iOS 15.1 as well - [DOWNLOAD](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/15.1%20(19B74).zip).

**Comment by filsv** [comment]
@01234abhishek Please reopen this issue if you still have a problem.

**Comment by LoSunny** [comment]
I'm having this error (The code signature version is no longer supported) when I'm trying to build with Xcode 12.4 (on 2015 MacBook air running MacOS 10.15.7) for iOS 15.5 (on iPhone 7 Plus) with [this](https://github.com/filsv/iOSDeviceSupport/blob/master/15.5.zip) installed

**Comment by yiusay** [comment]
For me, this was the solution. (Xcode 12.4 / MacOS Catalina 10.15.7) 
https://stackoverflow.com/questions/68467306/the-code-signature-version-is-no-longer-supported#comment124343283_68467307

The flag is "--generate-entitlement-der" as described in the original answer.
