### ISSUE TITLE
please add support for 14.8.1

### ISSUE THREAD

**Issue by mdtechcs** [filsv/iPhoneOSDeviceSupport#108]
I have recently received updates on my iphone 7 . Xcode is not supporting 14.8.1

Please add support for the same. Really thankful for your help.

**Comment by ianloubser** [comment]
I had the same problem, `14.8.1` wasn't working for me. But then just created a duplicate of the `14.8` folder in Xcode DeviceSupport and renamed to `14.8.1` now it works :)

**Comment by mdtechcs** [comment]
@ianloubser can you please zip your 14.8.1 folder and upload here please? I don't see 14.8 device support as well here.

Thanks in advance :)

**Comment by ianloubser** [comment]
I got 14.8 by doing the same process with 14.7.1, as mentioned in issue #100 
https://github.com/filsv/iPhoneOSDeviceSupport/issues/100#issuecomment-920588082

**Comment by mdtechcs** [comment]
@ianloubser thanks, it worked!
