### ISSUE TITLE
iOS 15.3  Support Files

### ISSUE THREAD

**Issue by BerkeAras** [filsv/iPhoneOSDeviceSupport#110]

**Comment by Mcrich23** [comment]
Yes pls

**Comment by irfan-429** [comment]
It's more than 2 weeks the issue opened and still not any updates from Apple.

**Comment by Mcrich23** [comment]
15.3 support is in Xcode 13.2.1

**Comment by irfan-429** [comment]
[see here](). it really doesn't  have. I have already 13.2.1. If you have with your Xcode. Can you share it with me?

**Comment by irfan-429** [comment]
<img width="1032" alt="Screenshot 2022-01-10 at 1 07 28 AM" src="https://user-images.githubusercontent.com/53349000/148699285-f5ec8e0b-936d-4513-b4d4-5cd128f72e97.png">

**Comment by JosephDuffy** [comment]
I've had success using the 15.2 support files after being renamed to 15.3

**Comment by Nododo** [comment]
> I've had success using the 15.2 support files after being renamed to 15.3

good job，aha

**Comment by martianmartian** [comment]
> I've had success using the 15.2 support files after being renamed to 15.3

what else is needed for this approach ? beside duplicating 15.2 then renaming it to 15.3 ?

**Comment by JosephDuffy** [comment]
> > I've had success using the 15.2 support files after being renamed to 15.3
> 
> 
> 
> what else is needed for this approach ? beside duplicating 15.2 then renaming it to 15.3 ?

I didn't have to do anything else.

**Comment by ChetanTechnource** [comment]
> I've had success using the 15.2 support files after being renamed to 15.3

Working

**Comment by surapol2** [comment]
>

**Comment by filsv** [comment]
Fellas iOS 15.3 support files are added, [you can it here](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/15.3.zip).

**Comment by Bullseye25** [comment]
Any one got 15.3.1

**Comment by waqaramjad** [comment]
same waiting 15.3.1
