### ISSUE TITLE
iOS 15.2.1 support

### ISSUE THREAD

**Issue by Nododo** [filsv/iPhoneOSDeviceSupport#113]
it's a new version，can anyone upload it？

thanks

**Comment by martianmartian** [comment]
same here. I'm new to iOS development, and updated my cell phone a few days ago, then I realized my MacBook does not have the latest support, so I cannot do cell phone testing anymore...

**Comment by surapol2** [comment]
> it's a new version，can anyone upload it？
> 
> thanks

**Comment by surapol2** [comment]
> it's a new version，can anyone upload it？
> 
> thanks

**Comment by franalt** [comment]
+1 does anyone have the support files? There is no XCode update avaiable either, where are we supposed to get these from?

**Comment by Nododo** [comment]
> +1 does anyone have the support files? There is no XCode update avaiable either, where are we supposed to get these from?

just rename 15.2 to 15.2.1

**Comment by filsv** [comment]
@Nododo @martianmartian @surapol2 @franalt Guys you have 2 options:

1) Just rename the folder to "15.2.1";
2) [Download 15.3 Support files here](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/15.3.zip);
3) You can also try to use [iOS 15.4 Support files from here](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/15.4.zip);

**Comment by Nododo** [comment]
> @Nododo @martianmartian @surapol2 @franalt Guys you have 2 options:
> 
> 1. Just rename the folder to "15.2.1";
> 2. [Download 15.3 Support files here](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/15.3.zip);
> 3. You can also try to use [iOS 15.4 Support files from here](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/15.4.zip);

thanks！
