### ISSUE TITLE
IOS 15.4.1 support files

### ISSUE THREAD

**Issue by sharukmsd** [filsv/iPhoneOSDeviceSupport#123]
Latest XCode 13.3.1 comes with 15.4 support only. Tried to rename 15.4 to 15.4.1 did not work. Please provide 15.4.1 supported files.

**Comment by lz-freedom** [comment]
+1

**Comment by ZePiao** [comment]
+1

**Comment by Dogayo** [comment]
+1

**Comment by sharukmsd** [comment]
> +1

I don't get it. What +1 ?

**Comment by zaferatli** [comment]
+1

**Comment by ViniSchonardie** [comment]
> just rename file to
> 
> 15.4 to 15.4.1
> 
> and restart xcode. its work for me.

Didnt worked for me.

**Comment by ViniSchonardie** [comment]
+1

**Comment by ViniSchonardie** [comment]
Ok i was able to find a solution for me:
Rename 15.4 to 15.4.1 -> restart xcode -> also restart the iphone...
than it worked...

**Comment by sharukmsd** [comment]
> 

Didn't worked already tried.

**Comment by shivanitp** [comment]
Did you get any solution for this?
I'm facing same issue

**Comment by harshvayuz** [comment]
I'm facing the same issue, please posted a solution if you found

**Comment by mike44x** [comment]
I have the same issue, looking for a hero who could help us :)

**Comment by trannghiahiep** [comment]
> Ok i was able to find a solution for me: Rename 15.4 to 15.4.1 -> restart xcode -> also restart the iphone... than it worked...

Ok, It's work for me

**Comment by ChenD17** [comment]
Problem solved after I disconnected my apple watch with my iphone and reconnected my iphone wich Xcode...

**Comment by yangyuanpeng** [comment]
您的邮件我已收到，我会尽快处理。谢谢。---杨远鹏

**Comment by kukadiyaAni** [comment]
+1

**Comment by sharukmsd** [comment]
_**Solution:**_
1. Try  Renaming 15.4 to 15.4.1 -> restart xcode -> also restart the iphone
2. Get Official Iphone Data cable (Xcode does not recognize iphone with local cables)
