### ISSUE TITLE
Request for IOS 12 device support folder .

### ISSUE THREAD

**Issue by Rahul0106231** [filsv/iPhoneOSDeviceSupport#13]
I have updated my iphone X to IOS 12 , now i need to debug an app on the device using xcode 9 . i dont want to download the complete new xcode 10 beta . Can someone post the IOS 12 device support folder ? Thanks in advance

**Comment by Apecice** [comment]
U can't  just download new IOS 12 version which can't  support by xcode 9.4 version.

**Comment by kretash** [comment]
I'm also interested in this, but if It can't be done I'll have to update.

**Comment by filsv** [comment]
@Apecice  no, you can, On my Xcode 9.4.1 (9F2000) it's works perfectly

**Comment by filsv** [comment]
@kretash  added, last non-beta, you can download it.
