### ISSUE TITLE
Add new Disk Image for latest iOS Version for iOS 16.6

### ISSUE THREAD

**Issue by SupratikRulz** [filsv/iPhoneOSDeviceSupport#172]

**Comment by JMRdev86** [comment]
pleaseee!!!

**Comment by wd-maria-ungur** [comment]
+1

**Comment by cbrzn** [comment]
i am also in the need of this 🙏 would be awesome if this is supported ser

**Comment by HelloItsMeAdm** [comment]
+1

**Comment by vietlinhtspt** [comment]
+1 :(

**Comment by hieuminh1810** [comment]
+1 please :(

**Comment by vietlinhtspt** [comment]
@hieuminh1810 https://drive.google.com/file/d/14jEnZrMWF0X53eDb7heZ5maLPLj73yiE/view

**Comment by vietlinhtspt** [comment]
[16.6.zip](https://github.com/filsv/iOSDeviceSupport/files/12214020/16.6.zip)
For anyone need

**Comment by vietlinhtspt** [comment]
@hieuminh1810 I tried it and it worked

**Comment by hieuminh1810** [comment]
> @hieuminh1810 I tried it and it worked

how do you have this file?

**Comment by yuriy3122** [comment]
+1

**Comment by wb-s** [comment]
Thanks

**Comment by ngunarola** [comment]
> [16.6.zip](https://github.com/filsv/iOSDeviceSupport/files/12214020/16.6.zip) For anyone need

Thank you! :)
