### ISSUE TITLE
Instructions for xcode 10

### ISSUE THREAD

**Issue by bsdkurt** [filsv/iPhoneOSDeviceSupport#19]
I tried to install 11.4.1 with xcode 10 following the current instructions, however xcode 10 doesn't recognize it. Does anyone know how to get 11.4.1 working with xcode 10?

**Comment by filsv** [comment]
@bsdkurt you get some error message? tried to restart Xcode? (please provide more info)

**Comment by bsdkurt** [comment]
Thanks for the response. I no longer have the need to get this working. Closing.
