### ISSUE TITLE
Required for iOS 12.2(16E227)

### ISSUE THREAD

**Issue by mmok1234** [filsv/iPhoneOSDeviceSupport#25]
Required for iOS 12.2(16E227) XS MAX

**Comment by invisible66** [comment]
me too..

**Comment by mateusz-** [comment]
I used [12.2 (16E5181e).zip](https://github.com/filsv/iPhoneOSDeviceSupport/blob/master/12.2%20(16E5181e).zip) in place of 12.2 (16E227) and don't seems to have any issues (at least, with iPad Air 2).

**Comment by Hannah-Alto** [comment]
@mateusz- didn't work for me on iPhone 6s

**Comment by invisible66** [comment]
I used [1.2 (16E226).zip](https://github.com/idbeny/DeviceSupport). It worked for me on Iphone 8plus.

**Comment by filsv** [comment]
Added last support files included (iOS 12.2)
