### ISSUE TITLE
iOS DeviceSupport 13.1 17A5837a

### ISSUE THREAD

**Issue by wuyang1314** [filsv/iPhoneOSDeviceSupport#33]
17A5837a 有吗

**Comment by filsv** [comment]
Hi @wuyang1314 try to rename a folder like this "13.1 (17A5837a)", and tell me if it's works.

**Comment by filsv** [comment]
@wuyang1314 does it work for you?

**Comment by mkll** [comment]
@filsv iPhone SE, iOS 13.1.2, folder renamed to "13.1 (17A860)", and it works.

**Comment by RodrigoJudice** [comment]
Works perfect
