### ISSUE TITLE
iOS 13.0 (17A577) 

### ISSUE THREAD

**Issue by thaiksoedev** [filsv/iPhoneOSDeviceSupport#35]
can i use ur supported file for ios 13.0(17A577)?

**Comment by filsv** [comment]
@thaiksoedev Hi, try to do this:
To get iOS 13.0 (****) works try to rename a folder from this "13.0" to "13.0 (17A577)".

It's will work for you, if not - open this issue again. 
Thanks and good luck ;)

**Comment by thaiksoedev** [comment]
@filsv It's not work for me , I was downloaded 13.1 but show same error .
