### ISSUE TITLE
iOS 13.2 please，great thanks

### ISSUE THREAD

**Issue by FernandoWei** [filsv/iPhoneOSDeviceSupport#39]

**Comment by crespoxiao** [comment]
@FernandoWei    https://github.com/Yatko/iOS-device-support-files/tree/master/13.2%20(17B5059f)

**Comment by filsv** [comment]
@FernandoWei  **[iOS 13.2](https://github.com/filsv/iPhoneOSDeviceSupport/blob/master/13.2.zip)**
