### ISSUE TITLE
Xcode 11.1 (AppStore Version) + 13.2 device support will crash Xcode when run project

### ISSUE THREAD

**Issue by codingiran** [filsv/iPhoneOSDeviceSupport#40]

**Comment by ArthurAvagyan** [comment]
I have the same issue, so still working on simulator :/

**Comment by shubham14896** [comment]
Same issue. Any solution @codingiran @ArthurAvagyan ?

**Comment by ArthurAvagyan** [comment]
No, just waiting for Xcode update, or someone to be solved this

**Comment by CottleCP** [comment]
Same issue xCode crashes when attempting to run on a hardware device

**Comment by togtokhdorj** [comment]
I have the same issue, so still working on simulator. How to fix this?

**Comment by edbond** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/1044/68007135-56483980-fc83-11e9-8fec-073109b2bdde.png">

**Comment by ArthurAvagyan** [comment]
Yup update arrived, i couldn't find it right in app store(line not showing update available), but just go trough [this](https://apps.apple.com/us/app/xcode/id497799835?mt=12) link(app store website url) and it will direct you to mac's app store. Updating... :)

**Comment by shubham14896** [comment]
Uninstall the current version, then download the new version, otherwise app store will stuck updating the current version

Shubham Gupta
+91-8527330381

**Comment by ArthurAvagyan** [comment]
@shubham14896 everything was about OK, just i waited for 5 min fu finish update, it kind of stucks a bit in the end when updating, but it continues

**Comment by shubham14896** [comment]
Give a try if not then try above approach !

Shubham Gupta
+91-8527330381

**Comment by codingiran** [comment]
Apple has release Xcode 11.2, update! 😄
