### ISSUE TITLE
Can we please get 13.3 support ? 

### ISSUE THREAD

**Issue by sourabhdadapure** [filsv/iPhoneOSDeviceSupport#41]

**Comment by klemensz** [comment]
I downloaded Xcode 11.3 Beta, but DeviceSupport files for 13.3 are not contained...

**Comment by klemensz** [comment]
Workaround: https://github.com/iGhibli/iOS-DeviceSupport/issues/76#issuecomment-558122778

**Comment by filsv** [comment]
@klemensz  try to rename 13.2 to 13.3, it's will work
