### ISSUE TITLE
Please, upload the iOS 12.4.3 support

### ISSUE THREAD

**Issue by eduardogarcialinio** [filsv/iPhoneOSDeviceSupport#43]

**Comment by antonmyrberg** [comment]
> To get iOS 13.1 (version) works try to rename a folder from this "13.1 (17A5821e)" to "13.1 (needed version)" eg. "13.1 (17A5844a)". The same for iOS 13.2 (version).

> Device Support files for Xcode, from iOS 6, up to 13.2.

Didn't this work? I got it working by following the guide.

**Comment by filsv** [comment]
@eduardogarcialinio  hi, just rename iOS 12 to 12.4.3
