### ISSUE TITLE
iOS 13.3 support

### ISSUE THREAD

**Issue by vivienseguy** [filsv/iPhoneOSDeviceSupport#45]
Hello again,
Renaming the 13.2 folder to 13.3 (with or without the model number in parenthesis) did not do the trick for me. Has it worked for anyone else?
Thank you for your attention.
Vivien

**Comment by MaanuVazquez** [comment]
The support files for `13.3` are already on the repo, but whenever xcode tries to run the app in the device it just crashes, anyone with the same problem?

**Comment by vivienseguy** [comment]
It worked for me ! Thank you very much to the team !

**Comment by jaimejazarenoiii** [comment]
> The support files for `13.3` are already on the repo, but whenever xcode tries to run the app in the device it just crashes, anyone with the same problem?

Same. Any explanation here?

**Comment by vivienseguy** [comment]
Follow up: Xcode does not seem to recognize the support files anymore for me. It worked for a day and then suddenly started to show me the message about missing support files again...

**Comment by oyb81076** [comment]
![屏幕快照 2019-12-20 下午6 53 10](https://user-images.githubusercontent.com/6634415/71250201-05d38b00-235a-11ea-99d7-6f9573ef6093.png)

**Comment by salmanullahkhan15** [comment]
I am getting this error after add folder 13.3.

Error: dyld_shared_cache_extract_dylibs failed

**Comment by andrea-couto** [comment]
> I am getting this error after adding folder 13.3.
> 
> Error: dyld_shared_cache_extract_dylibs failed

I am also getting this error after adding 13.3 and changing its name to "‎13.3 (17C54)"

**Comment by tospik1** [comment]
> > I am getting this error after adding folder 13.3.
> > Error: dyld_shared_cache_extract_dylibs failed
> 
> I am also getting this error after adding 13.3 and changing its name to "‎13.3 (17C54)"

The same.

**Comment by bcbroom** [comment]
I also had the dyld cache error, but fixed it using these steps https://github.com/iGhibli/iOS-DeviceSupport/issues/79#issuecomment-568659099

**Comment by filsv** [comment]
@oyb81076  try to rename the folder to 13.3 (17C54).

**Comment by filsv** [comment]
@andrea-couto  which version of iOS 13.3 are you trying to build? (are you sure it's 17C54?)

**Comment by filsv** [comment]
Hey guys please try new recently updated iOS [13.3 support files](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/13.3.zip)
