### ISSUE TITLE
my xcode cant detect the ios13.3 device support file. 

### ISSUE THREAD

**Issue by thefudgeishot** [filsv/iPhoneOSDeviceSupport#46]
After I installed the package with the method stated in the git page, my Xcode still can't find the ios 13.3 support file. Have I done something wrong or is there something I'm not reading right?

**Comment by nickpoulos** [comment]
Nope, same here. Pasted /13.3/ into the correct folder, restarted XCode. But it is still not listed in my Target drop down list, only up to 13.2.

**Comment by janakmshah** [comment]
@nickpoulos Which target drop down list? The method described only adds support to build for 13.3 physical devices, it won't add a 13.3 simulator for you.

**Comment by janakmshah** [comment]
The method described won't provide more options in the Deployment target drop down. That's the minimum supported version.
The method adds support to build to 13.3 physical devices. There is not drop down to specify that.

**Comment by SreekanthGudisi** [comment]
Hi,
Same problem here. Not showing iOS 13.3
Im running on iOS 13.3 physical device but I couldn't run its showing *Can't install the ****app*

**Comment by filsv** [comment]
@janakmshah is right, @thefudgeishot / @nickpoulos / @SreekanthGudisi please read his comment here (https://github.com/filsv/iPhoneOSDeviceSupport/issues/46#issuecomment-584547329). Support files are just for real device support not for simulator.

**Comment by SreekanthGudisi** [comment]
Hi @filsv 
I have tried on physical device only but no luck
