### ISSUE TITLE
Catalina Relocation of Applications for readme

### ISSUE THREAD

**Issue by TRGoCPftF** [filsv/iPhoneOSDeviceSupport#48]
As of MacOS 10.15 it appears they moved the way applications are stored (I recently moved from 10.14.6 -> 10.15.3 

The New location is:
`/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/`

**Comment by filsv** [comment]
@TRGoCPftF It's the same location, just you added a prefix on your hard drive.

**Comment by TRGoCPftF** [comment]
Interesting. It was only present change after upgrading from late Mojave to Catalina without me manually changing anything. Assumed it was a structural change. My B <3
