### ISSUE TITLE
Please add iOS 13.3.1

### ISSUE THREAD

**Issue by marloncepeda** [filsv/iPhoneOSDeviceSupport#49]
Please add iOS 13.3.1

**Comment by mkll** [comment]
This is not required. You can use 13.3.

**Comment by ooanishoo** [comment]
@mkll when i use 13.3, it says:  `dyld_shared_cache_extract_dylibs failed`
Can you please help ?

**Comment by mkll** [comment]
Sorry, I don't know how to help you, I don't have any problems. Xcode 10.3, macOS 10.13.6, iOS 13.3.1, Swift 5.0.

**Comment by Fatehkhann** [comment]
Please add iOS 13.3.1. Can't get my apps work with just 13.3

**Comment by marloncepeda** [comment]
> Sorry, I don't know how to help you, I don't have any problems. Xcode 10.3, macOS 10.13.6, iOS 13.3.1, Swift 5.0.

mmm ... it is possible that the version of xcode 10.3 does not generate errors, try updating to xcode 10.3. In fact, I have version 10.2.1 (10E1001)

**Comment by mkll** [comment]
@marloncepeda Updating to Xcode 10.3 gives you yet another benefit — Swift 5.0. But if you take into account that starting from April, all apps sent to the App Store must be built with Xcode 11, then all this doesn’t make much sense.

> Starting April, 2020, all iPhone and iPad apps submitted to the App Store will need to be built with the iOS 13 SDK or later.
https://developer.apple.com/ios/submit/

**Comment by marloncepeda** [comment]
> Updating to Xcode 10.3 gives you yet another benefit — Swift 5.0. But if you take into account that starting from April, all apps sent to the App Store must be built with Xcode 11, then all this doesn’t make much sense.

I understand it then it is best to update mojave on the spot to avoid further problems in the future.

**Comment by mkll** [comment]
@marloncepeda If your mac hardware allows, you definitely must update to Mohave or Catalina and Xcode 11.
