### ISSUE TITLE
Request 11.2.5 (15D60) support

### ISSUE THREAD

**Issue by iTofu** [filsv/iPhoneOSDeviceSupport#5]

**Comment by iTofu** [comment]
And where could I find the latest DeveloperDiskImage.dmg file?

**Comment by jkmathew** [comment]
you can fid it in the path `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform`

**Comment by filsv** [comment]
@iTofu hi, you can use iOS 11.3 which mostly the same, if it's not - help please let me know - I'll reopen this issue and will upload this version. thanks.
