### ISSUE TITLE
please Add iOS SDK  13.4

### ISSUE THREAD

**Issue by senjoeson** [filsv/iPhoneOSDeviceSupport#50]
please Add iOS SDK  13.4.

**Comment by mishalazarev2020** [comment]
Please add 13.4 beta versions please

**Comment by filsv** [comment]
@senjoeson / @mishalazarev2020 Today will be.

**Comment by filsv** [comment]
@senjoeson  / @mishalazarev2020 [Here](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/13.4.zip) 13.4 Support files
