### ISSUE TITLE
iOS 13.3.1 (17D50) crash with Xcode 11.1

### ISSUE THREAD

**Issue by SrNaza** [filsv/iPhoneOSDeviceSupport#51]
Well, I updated my IOS DeviceSupport with the file iOS13.3.zip, I guess I need the files of this new version ... My project still cannot be executed with xcode 11.1 ++, maybe there is another configuration that I have to do so that it doesn't crash the xcode when compiling with my device ?

**Comment by mehulparmar4ever** [comment]
same issue with me.

**Comment by eabuslaiman30** [comment]
Any update on this? The same here.

**Comment by mkll** [comment]
Why do you need this stuff if you have Xcode 11 guys? Latest Xcode 11 has all you need to build on device with latest iOS release. Just update Xcode.

**Comment by SrNaza** [comment]
i can't update my xcode more than 11.1+ , well I shouldn't because the project where i'm working require max 11.1 for the moment

**Comment by mkll** [comment]
@SrNaza Oh, sorry for that. Could you describe in short what kind of constraints prevents you from updating? Any breakdowns in the later SDKs? Just interested.

**Comment by jose2016** [comment]
Same issue with ios iOS 13.3.1 (17D50) Mackbook 10.13.6
XCODE dyld_shared_cache_extract_dylibs failed

I can't update my xcode. Any update?

**Comment by mehulparmar4ever** [comment]
Yes, I find one solution. It is working awesome. Super Speed in my MacBook Pro.

Kindly follow below link & Install Catalina MacOS in your Mac. See attached screenshot of my MacBook system. No need to do this kind of stuff (Means IOS DeviceSupport), It will work on full speed. 

Enjoy have a great day. (If anyone need help/guidance let me know, I will share my exp with you)

[http://dosdude1.com/catalina/
![Screenshot 2020-03-04 at 11 30 35 AM](https://user-images.githubusercontent.com/7687920/75849737-9ecb5b80-5e0b-11ea-8ae1-b0f8ff966216.png)
](url)

**Comment by bakhadev** [comment]
> 
> 
> Yes, I find one solution. It is working awesome. Super Speed in my MacBook Pro.
> 
> Kindly follow below link & Install Catalina MacOS in your Mac. See attached screenshot of my MacBook system. No need to do this kind of stuff (Means IOS DeviceSupport), It will work on full speed.
> 
> Enjoy have a great day. (If anyone need help/guidance let me know, I will share my exp with you)
> 
> [http://dosdude1.com/catalina/ ![Screenshot 2020-03-04 at 11 30 35 AM](https://user-images.githubusercontent.com/7687920/75849737-9ecb5b80-5e0b-11ea-8ae1-b0f8ff966216.png) ](url)

spam

**Comment by mehulparmar4ever** [comment]
> > Yes, I find one solution. It is working awesome. Super Speed in my MacBook Pro.
> > Kindly follow below link & Install Catalina MacOS in your Mac. See attached screenshot of my MacBook system. No need to do this kind of stuff (Means IOS DeviceSupport), It will work on full speed.
> > Enjoy have a great day. (If anyone need help/guidance let me know, I will share my exp with you)
> > [http://dosdude1.com/catalina/ ![Screenshot 2020-03-04 at 11 30 35 AM](https://user-images.githubusercontent.com/7687920/75849737-9ecb5b80-5e0b-11ea-8ae1-b0f8ff966216.png) ](url)
> 
> spam

Hey, Why spam? @bakhadev , 

What happen bro? Have you try anything or just comment without any knowledge!! 
You looks like android developer & Do you have ever tried any step in Mac or in iOS ?
Please don't comment without experience such real issue.

Sorry If I hurt you.

**Comment by bakhadev** [comment]
Because, people needs resolve problem without installing or update Mac OS and Xcode.

**Comment by bakhadev** [comment]
> 
> 
> > > Yes, I find one solution. It is working awesome. Super Speed in my MacBook Pro.
> > > Kindly follow below link & Install Catalina MacOS in your Mac. See attached screenshot of my MacBook system. No need to do this kind of stuff (Means IOS DeviceSupport), It will work on full speed.
> > > Enjoy have a great day. (If anyone need help/guidance let me know, I will share my exp with you)
> > > [http://dosdude1.com/catalina/ ![Screenshot 2020-03-04 at 11 30 35 AM](https://user-images.githubusercontent.com/7687920/75849737-9ecb5b80-5e0b-11ea-8ae1-b0f8ff966216.png) ](url)
> > 
> > 
> > spam
> 
> Hey, Why spam? @bakhadev ,
> 
> What happen bro? Have you try anything or just comment without any knowledge!!
> You looks like android developer & Do you have ever tried any step in Mac or in iOS ?
> Please don't comment without experience such real issue.
> 
> Sorry If I hurt you.

Because, people needs resolve problem without installing MacOS or Xcode.

**Comment by mehulparmar4ever** [comment]
> > > > Yes, I find one solution. It is working awesome. Super Speed in my MacBook Pro.
> > > > Kindly follow below link & Install Catalina MacOS in your Mac. See attached screenshot of my MacBook system. No need to do this kind of stuff (Means IOS DeviceSupport), It will work on full speed.
> > > > Enjoy have a great day. (If anyone need help/guidance let me know, I will share my exp with you)
> > > > [http://dosdude1.com/catalina/ ![Screenshot 2020-03-04 at 11 30 35 AM](https://user-images.githubusercontent.com/7687920/75849737-9ecb5b80-5e0b-11ea-8ae1-b0f8ff966216.png) ](url)
> > > 
> > > 
> > > spam
> > 
> > 
> > Hey, Why spam? @bakhadev ,
> > What happen bro? Have you try anything or just comment without any knowledge!!
> > You looks like android developer & Do you have ever tried any step in Mac or in iOS ?
> > Please don't comment without experience such real issue.
> > Sorry If I hurt you.
> 
> Because, people needs resolve problem without installing MacOS or Xcode.

I can understand it. @bakhadev 

I tried all possible solution. Then after Above is only option left for me. You can get latest OS experience in your older MacBook. I hope you get my point. :-)

**Comment by AmrAdelMohammed** [comment]
I updated xcode to 13.3.1 and still have the problem
any onne can send me  iOS 13.3.1 (17D50) the support file or have a solution

**Comment by filsv** [comment]
@SrNaza @mehulparmar4ever @eabuslaiman30 @mkll @jose2016 Hi guys, try last one 13.4 support files from **[HERE](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/13.4.zip)**.
