### ISSUE TITLE
iOS 13.5 Device Support

### ISSUE THREAD

**Issue by adbdehghan** [filsv/iPhoneOSDeviceSupport#56]
Please add iOS 13.5 device support.
Thanks

**Comment by mvascs** [comment]
i'm waiting too!!

**Comment by jamie1192** [comment]
Pending here https://github.com/filsv/iPhoneOSDeviceSupport/pull/58

**Comment by filsv** [comment]
@jamie1192 Merged, thanks! 
@adbdehghan / @mvascs [iOS 13.5 Device Support](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/13.5.zip)
