### ISSUE TITLE
Please add support for 13.4.1 (17E262)

### ISSUE THREAD

**Issue by dougcodes** [filsv/iPhoneOSDeviceSupport#57]
Please add support for 13.4.1 (17E262)

**Comment by schricb** [comment]
Agreed! Thanks

**Comment by fad0** [comment]
Someone on StackOverflow renamed 13.4 to 13.4.1 and it worked.  It worked for me too.

**Comment by iCanHazCoFFee** [comment]
It worked for me when I renamed the folder to 13.4.1 (17E262).

**Comment by filsv** [comment]
@dougcodes / @schricb 
Yes guys, please read [READ.md](https://github.com/filsv/iPhoneOSDeviceSupport/blob/master/README.md) clear:

"To get iOS 13.1 (version) works try to rename a folder from this "13.1 (17A5821e)" to "13.1 (needed version)" eg. "13.1 (17A5844a)". The same for iOS 13.+ (version)."

**Comment by dougcodes** [comment]
@filsv  Why did you close this? I tried renaming it and still get the error and others do too.

**Comment by filsv** [comment]
> @filsv  Why did you close this? I tried renaming it and still get the error and others do too.

@dougcodes 
Please attach your error, and how you renaming the folder ?

**Comment by dougcodes** [comment]
Error when running: dyld_shared_cache_extract_dylibs failed

I tried the following:

1) Copied the folder 13.4 to DeviceSupport, and rename it to: 13.4.1 (17E262)
2) Created symlink from 13.4 to 13.4.1 (17E262)

None worked.

**Comment by iCanHazCoFFee** [comment]
You need to place your folder containing the "DeveloperDiskImage.dmg" & "DeveloperDiskImage.dmg.signature" here:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/13.4.1 (17E262)

What version of Xcode are you using ?

**Comment by dougcodes** [comment]
Yes I have placed the folder in the location you mentioned.
Xcode version: Version 10.1 (10B61)

**Comment by iCanHazCoFFee** [comment]
I remember having similar issues with previous versions of Xcode. My problems had been solved by updating to Xcode 10.3 (10G8).

**Comment by LudoviKush** [comment]
I solved just downloading the 13.4 one, unzipping it, putting on the iOS Device Support folder and renaming it to 13.4.1 (17E262).
Make sure you have Xcode closed when your putting into.

**Comment by filsv** [comment]
@dougcodes Has you solved your issue?

**Comment by dougcodes** [comment]
@filsv  - I got it working by updating mac os and xcode. Not sure if that is a good solution since some people might not be able to update os.

**Comment by filsv** [comment]
@dougcodes Thanks for your comment, probably it was some issue with an Xcode cache.
