### ISSUE TITLE
Latest releases can not download

### ISSUE THREAD

**Issue by Weever** [filsv/iPhoneOSDeviceSupport#59]
Xcode iPhoneOS DeviceSupport (6.0 - 13.5)

Latest releases:

iOS 13.1 - Download 
iOS 13.2 - Download 
iOS 13.3 - Download 
iOS 13.4 - Download 
iOS 13.5 - Download

like this：
https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/13.5.zip

can open：
https://github.com/filsv/iPhoneOSDeviceSupport/blob/master/13.5.zip

and 13.5 now is from Xcode beta version

**Comment by filsv** [comment]
Hi @Weever , sorry, not understand which issue do you have?

**Comment by Weever** [comment]
some time open link：https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/13.5.zip

**Comment by Weever** [comment]
![8B690038-6028-4302-A004-99BF567E48EC](https://user-images.githubusercontent.com/970923/83969440-a286e680-a902-11ea-87fe-7e904df763f1.png)

**Comment by Weever** [comment]
maybe is github‘s issue!

**Comment by filsv** [comment]
@Weever do you use VPN? it's can be related to it. But try to download files on Mac not on the iPhone.

**Comment by filsv** [comment]
@Weever I'll close this issue, if you still have the same issue we will reopen it.
