### ISSUE TITLE
Please add support for 13.6

### ISSUE THREAD

**Issue by leleyinhangjia** [filsv/iPhoneOSDeviceSupport#60]

**Comment by YurchukV** [comment]
https://github.com/YurchukV/iPhoneOSDeviceSupport

https://github.com/filsv/iPhoneOSDeviceSupport/pulls

**Comment by filsv** [comment]
@leleyinhangjia [Here](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/13.6.zip). Thanks to @YurchukV .
