### ISSUE TITLE
dyld_shared_cache_extract_dylibs failed iOS 13.5.1 (17F80) iPhone XR , XCode 10.1 (10B61)

### ISSUE THREAD

**Issue by felipemobile** [filsv/iPhoneOSDeviceSupport#63]
I am facing this issue of dyld_shared_cache_extract_dylibs failed iOS 13.5.1 (17F80) iPhone XR XCode 10.1 (10B61)

- XCode was Closed
- Renamed folder 13.5 ~> 13.5.1 (17F80)

Any ideias?

**Comment by iCanHazCoFFee** [comment]
I'm running Xcode 10.3 without any issues. Try that.

**Comment by felipemobile** [comment]
There is no Xcode update available for MacBook Pro (13-inch, Early 2011).

**Comment by iCanHazCoFFee** [comment]
You can follow this guide: https://codewithchris.com/xcode-update/

**Comment by filsv** [comment]
@iCanHazCoFFee thanks for your help-comment to @felipemobile .
