### ISSUE TITLE
Xcode 11.1 crashes when I try to run the App on iPhone 11 Pro Max iOS 13.6 

### ISSUE THREAD

**Issue by amrutha786** [filsv/iPhoneOSDeviceSupport#66]
I have added iOS 13.6 device support files to Xcode 11.1 as per the given instructions but when I try to run my App from Xcode 11.1 on iPhone 11 Pro Max iOS 13.6, Xcode crashes. 

Can you please tell me where I am going wrong?

**Comment by filsv** [comment]
@amrutha786 Hi! try these steps:

Click "Show package contents" of the ".xcworkspace" file, in the workspace directory and deleted "xcuserdata" folder. 
This resolved the crash for me. 

Comment me back if its help, thanks.

**Comment by filsv** [comment]
@amrutha786 does it help?

**Comment by amrutha786** [comment]
@filsv I do not have a .xcworkspace but instead, i have .xcodeproj so i went ahead and deleted the xcuserdata folder but the issue still exists

**Comment by amrutha786** [comment]
@filsv Is there a workaround for the crash that i am seeing on Xcode 11.1 when running on iPhone 11 Pro Max iOS 13.6

**Comment by filsv** [comment]
@amrutha786 What exact iOS version do you have?
You can found it here: Settings -> General -> About -> Tap on "Software Version" -> It's will be changed from "13.6" to "13.6 (17F80) or something similar".

Please attach version here in the comment.

**Comment by filsv** [comment]
@amrutha786 Try this:
[13.6.zip](https://github.com/filsv/iPhoneOSDeviceSupport/files/5017483/13.6.zip)

If this will not help try to rename 13.6 to 13.6 (your iPhone version), eg. 13.6(17F80).

**Comment by amrutha786** [comment]
@filsv 
The Software Version is 13.6(17G68)

**Comment by filsv** [comment]
@amrutha786 try to rename "13.6" folder to "13.6 (17G68)"

**Comment by amrutha786** [comment]
@filsv I named the folder exactly same cleared the xcuserdata in .xcodeproj and restarted the Xcode, but still, Xcode 11.1 crashes, 

Surprisingly i have another device iPhone 7 (iOS 13.6 (17G68) and the code works fine on that device.

**Comment by filsv** [comment]
@amrutha786 strange, maybe it's some issue with the device 🤷‍♂️

**Comment by amrutha786** [comment]
@filsv I restarted the device and still the issue exists.

**Comment by filsv** [comment]
@amrutha786 Still there is an issue?
