### ISSUE TITLE
Can i get Device Support files for iOS 13.7 (17H35) 

### ISSUE THREAD

**Issue by amrutha786** [filsv/iPhoneOSDeviceSupport#68]
Hi 

Can I get Device Support files for iOS 13.7 (17H35) to run the App from Xcode 11.1 

Thank you

**Comment by j1mr10rd4n** [comment]
see #67

**Comment by amrutha786** [comment]
Thank you @j1mr10rd4n But how do i get the Zip file (i see that the pull request is still pending)

**Comment by j1mr10rd4n** [comment]
If #67 still isn't merged, you can get the zip directly from [the iOS-13.7 branch on my fork](https://github.com/j1mr10rd4n/iPhoneOSDeviceSupport/tree/iOS-13.7)

**Comment by gunantosteven** [comment]
> If #67 still isn't merged, you can get the zip directly from [the iOS-13.7 branch on my fork](https://github.com/j1mr10rd4n/iPhoneOSDeviceSupport/tree/iOS-13.7)

Thank you, I have no idea why server for downloading xcode 11.7 so slow.

**Comment by filsv** [comment]
@j1mr10rd4n sorry for the waiting time - [merged](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/13.7.zip).
