### ISSUE TITLE
iOS 14 doesn't work with Xcode 11.7

### ISSUE THREAD

**Issue by jlcvp** [filsv/iPhoneOSDeviceSupport#69]
Getting this error
<img width="421" alt="image" src="https://user-images.githubusercontent.com/2317417/92633576-594f8580-f2a9-11ea-9cea-341830da73ce.png">

I've already unpaired the device, re-trusted, etc. Also tried to use 14.0 folder from Xcode12 beta6.

**Comment by filsv** [comment]
@jlcvp Not sure, but it can be 'beta' issue.

**Comment by jlcvp** [comment]
yeah, it can be. Working fine with xcode12-beta6

**Comment by CivelXu** [comment]
Beta 8 not works. 😭

**Comment by azouts** [comment]
GM doesn't work either.

**Comment by IMKiller** [comment]
help

**Comment by qtdevel** [comment]
It seems that it's impossible now to debug iOS 14 from Xcode with version below 12.
[Xcode 12 Release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes) say:

> Xcode 12 now encrypts the connection between Xcode and paired devices, protecting against an attacker in a privileged network position executing arbitrary code on connected iOS, iPadOS, watchOS, or tvOS devices during a remote debug session. (60386733)
> These security benefits are available when Xcode 12 connects to devices running iOS 14, iPadOS 14, watchOS 7, tvOS 14, or later versions. **These OS versions also refuse debugger connections from older Xcode releases.** Xcode 12 continues to support debugging for older OS versions, but without the new encryption.

Very bad.

**Comment by jlcvp** [comment]
> It seems that it's impossible now to debug iOS 14 from Xcode with version below 12.
> [Xcode 12 Release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes) say:
> 
> > Xcode 12 now encrypts the connection between Xcode and paired devices, protecting against an attacker in a privileged network position executing arbitrary code on connected iOS, iPadOS, watchOS, or tvOS devices during a remote debug session. (60386733)
> > These security benefits are available when Xcode 12 connects to devices running iOS 14, iPadOS 14, watchOS 7, tvOS 14, or later versions. **These OS versions also refuse debugger connections from older Xcode releases.** Xcode 12 continues to support debugging for older OS versions, but without the new encryption.
> 
> Very bad.

so Sad it stopped working, I'll be forced to upgrade my legacy code to work on xcode12. We could update the Readme.md to state it's possible to build and deploy on iOS14 devices but it'll be impossible to debug

**Comment by filsv** [comment]
@jlcvp & @qtdevel Thanks, added in readme.

**Comment by typfel** [comment]
I found this article useful, describing a few techniques for working around this issue https://medium.com/better-programming/debugging-on-ios-14-with-xcode-11-d332f12f49dd
