### ISSUE TITLE
Request for iOS 11.3 (15E216)

### ISSUE THREAD

**Issue by sutee9** [filsv/iPhoneOSDeviceSupport#7]
The files of the current 11.3 release are still missing. Would be great if you could add them.

**Comment by sutee9** [comment]
iOS 11.3 (15E216)

**Comment by ardalahmet** [comment]
@sutee9 iOS 11.3 (15E217): https://drive.google.com/open?id=1l0vLzKK4xgyxp6iCYWzMmdW1HiDJKeMx

**Comment by albertml** [comment]
11.3 (15E5178d) will still work

**Comment by sutee9** [comment]
Thanks ardalahmet! 

albertml, no I tried and it didn't.

**Comment by AlexZd** [comment]
My iPhone X is iOS 11.3 (15E216), I tried iOS 11.3 (15E217) and it didn't work. I thought later version will work with version below.

**Comment by bernardo11rex** [comment]
I would be happy to have the 15F5049c because my app is needing that in order to execute.

**Comment by GemmaLouise** [comment]
Where do you put this folder to make it work?

**Comment by AlexZd** [comment]
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform`

**Comment by bernardo11rex** [comment]
If you have the last version of Xcode, I that version is already there, the one that is not is iOS 11.4.


B11R

Game Critic

Skype: Bernardo11Rex.

Cel:+1 9292559637

https://www.linkedin.com/in/bernardo-g-1bb1018b/

On Apr 25, 2018, at 7:16 AM, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform

**Comment by usmaem** [comment]
@GemmaLouise 
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport`

**Comment by nesta219** [comment]
I can't upgrade my work laptop to OSX 10.13 due to compatibility issues with business critical software, so I couldn't update my Xcode to the newest version. This worked like a charm as a workaround.  Thanks everybody.

**Comment by reza7rm** [comment]
@ardalahmet tnx a lot, have you got iOS 11.3.1(15E302) as well?

**Comment by ardalahmet** [comment]
@reza7rm Unfortunately, no.

**Comment by AndreFWeber** [comment]
@reza7rm  @ardalahmet I am using an iPad Air iOS 11.3.1(15E302) and these steps worked for me :D

**Comment by dseeker** [comment]
@AlexZd so you just copy those files and compile the same way? or did you change any settings in Xcode to allow it to compile to that version? I'm using xcode 9.0.1 and trying to compile to 11.4, not sure what else I need to do other than copy the directory

**Comment by Roxky** [comment]
Need 11.4 :(

**Comment by ShafiqEssani** [comment]
@Roxky you can download it from here

**Comment by federhico** [comment]
11.4.1 (15G77)   ???

**Comment by federhico** [comment]
11.4.1 (15G77) ???

**Comment by filsv** [comment]
@federhico you can download it here - https://github.com/filsv/iPhoneOSDeviceSupport/blob/master/11.4.1%20(15G77).zip

**Comment by filsv** [comment]
> Need 11.4 now lol if anyone knows.

You can download 11.4 (15F79) from here - https://github.com/filsv/iPhoneOSDeviceSupport/blob/master/11.4%20(15F79).zip

**Comment by filsv** [comment]
> The files of the current 11.3 release are still missing. Would be great if you could add them.

11.3 release from Xcode 10, you can download it from here - https://github.com/filsv/iPhoneOSDeviceSupport/blob/master/11.3.zip
