### ISSUE TITLE
Missing Developer support files for iOS 14.2 beta

### ISSUE THREAD

**Issue by palmcrust** [filsv/iPhoneOSDeviceSupport#70]
I upgraded my phone for iOS 14.2 beta and cannot access the phone from Xcode. Tried copying iOS 14.0 to iOS 14.2 — didn't work. The Xcode fails to prepare the phone for development.
I am currently with Xcode 12.0 and prefer not to install a Xcode 12.2 beta.
Please, upload iOS 14.2 developer support files.

**Comment by Yaanco** [comment]
the same with you

**Comment by filsv** [comment]
@palmcrust Hi, added, [download link](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/14.2.zip).
