### ISSUE TITLE
IOS 14.1 and IOS 14.2 support

### ISSUE THREAD

**Issue by cyberCBM** [filsv/iPhoneOSDeviceSupport#72]
Hi,

It has been observed that Xcode 12.2 beta 3 version has support added for IOS 14.1 and IOS 14.2

I have attached both which I was able to retrieve during my investigation, Hope this will help.

[14.1.zip](https://github.com/filsv/iPhoneOSDeviceSupport/files/5418014/14.1.zip)
[14.2.zip](https://github.com/filsv/iPhoneOSDeviceSupport/files/5418016/14.2.zip)

Thanks for the documenting such instances that lead me to solution to the problem I was facing for development using xCode 12.0.1 with latest IOS 14.1  on iPhone 11 pro.

**Comment by LinBrong** [comment]
Good Man

**Comment by A-M-j** [comment]
thank you man

**Comment by kmitj** [comment]
not working with iphone XR ios 14.1

**Comment by filsv** [comment]
@cyberCBM Thanks, added: [iOS 14.1](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/14.1.zip), [iOS 14.2](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/14.2.zip)

**Comment by abdullah4one** [comment]
My issue was "Your Xcode version may be too old for your iOS version"
and i implemented your suggestion

Download iOS 14.2 Support Files
Unzip it
Put unzipped folder in into path:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/
Restart Xcode

then it showing this error message

Unable to locate DeviceSupport directory with suffix 'Symbols'. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!


What to do?
