### ISSUE TITLE
Unable to locate DeviceSupport directory with suffix 'Symbols'.

### ISSUE THREAD

**Issue by abdullah4one** [filsv/iPhoneOSDeviceSupport#74]
My issue was "Your Xcode version may be too old for your iOS version"<Br> and i implemented your suggestion<br>
Download iOS 14.2 Support Files
Unzip it
Put unzipped folder in into path:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/
Restart Xcode
<br> then it showing this error message<br>
 
Unable to locate DeviceSupport directory with suffix 'Symbols'. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!
<br><br>What to do?

**Comment by filsv** [comment]
@abdullah4one Probably you should update your Xcode version to the latest one, try it first. Because your Xcode version can be really too old for these iOS version.
