### ISSUE TITLE
An error was encountered while attempting to communicate with this device. (The service is invalid.)

### ISSUE THREAD

**Issue by harrain** [filsv/iPhoneOSDeviceSupport#76]
An error was encountered while attempting to communicate with this device. (The service is invalid.)

Domain: com.apple.dtdevicekit

Code: -402653150

Failure Reason: Please try rebooting and reconnecting the device. (0xE8000022).

User Info: {

    DVTRadarComponentKey = 487927;

    "com.apple.dtdevicekit.stacktrace" = (

0   DTDeviceKitBase                     0x0000000124576047 DTDKCreateNSError + 109

1   DTDeviceKitBase                     0x0000000124576749 DTDKAMDErrorToNSError + 792

	2   DTDeviceKitBase                     0x000000012458766c 63-[DTDKRemoteDeviceConnection startFirstServiceOf:unlockKeybag:]blockinvoke + 301

	3   DTDeviceKitBase                     0x0000000124586e3b 48-[DTDKRemoteDeviceConnection futureWithSession:]blockinvoke3 + 22

4   DTDeviceKitBase                     0x0000000124578abf _DTDKExecuteInSessionblockinvoke2 + 35

5   DTDeviceKitBase                     0x0000000124577ef3 _DTDKExecuteWithConnectionblockinvoke2 + 473

6   DTDeviceKitBase                     0x0000000124577cf1 _DTDKExecuteWithConnectionblockinvoke + 106

	7   libdispatch.dylib                   0x00007fff6f7aa63d dispatchclientcallout + 8

8   libdispatch.dylib                   0x00007fff6f7b6129 dispatchlanebarriersyncinvokeandcomplete + 60

	9   DVTFoundation                       0x000000010a9bbc60 DVTDispatchBarrierSync + 208

	10  DVTFoundation                       0x000000010a993088 -[DVTDispatchLock performLockedBlock:] + 64

	11  DTDeviceKitBase                     0x0000000124577bf2 DTDKExecuteWithConnection + 226

	12  DTDeviceKitBase                     0x0000000124578929 DTDKExecuteInSession + 376

	13  DTDeviceKitBase                     0x0000000124586d70 48-[DTDKRemoteDeviceConnection futureWithSession:]blockinvoke2 + 112

14  DVTFoundation                       0x000000010a9b99ca DVTCALLINGCLIENTBLOCK + 7

	15  DVTFoundation                       0x000000010a9bb0a2 DVTDispatchAsyncblockinvoke + 809

	16  libdispatch.dylib                   0x00007fff6f7a95f8 dispatchcallblockandrelease + 12

17  libdispatch.dylib                   0x00007fff6f7aa63d dispatchclientcallout + 8

	18  libdispatch.dylib                   0x00007fff6f7b08e0 dispatchlaneserialdrain + 602

	19  libdispatch.dylib                   0x00007fff6f7b1396 dispatchlaneinvoke + 385

20  libdispatch.dylib                   0x00007fff6f7b96ed dispatchworkloopworkerthread + 598

21  libsystempthread.dylib             0x00007fff6f9ea611 pthreadwqthread + 421

	22  libsystempthread.dylib             0x00007fff6f9ea3fd start_wqthread + 13

);

}
-

Anyone having the same issue.Below are the Configuration Details. 
MacOS: Mojave 10.14.6
Xcode: 11.3.1
iOS 14.1, 14.2

Please assist.

Thanks
Mamta

**Comment by mrugeshtank** [comment]
For debugging in iOS 14 devices you need Xcode 12 atleast. Cause Apple have updated their code for debugging apps on iOS14 and that is not compatible on older version of Xcode

**Comment by filsv** [comment]
@mrugeshtank Thank you for mentioning this, added in the readme. @harrain try to update to Xcode 12.

**Comment by brand2021** [comment]
plz add - ios 15.5

**Comment by ReneVella** [comment]
Hi, appreciate a lot if you could add in the IOS18 device support file ?  many thanks
