### ISSUE TITLE
any update on files for 14.2.1?

### ISSUE THREAD

**Issue by sstadtl** [filsv/iPhoneOSDeviceSupport#77]
my ip12 updated to 14.2.1, and now i am running into the same problem again.
can you add the files for 14.2.1? 

can i help somehow?

<details>
  <summary>Click to expand full error in Xcode</summary>

Failed to prepare device for development.
Domain: com.apple.dtdevicekit
Code: 806
Recovery Suggestion: If you are certain that Xcode supports development on this device, try disconnecting and reconnecting the device.
User Info: {
    AssociatedMobileDeviceFunction = AMDeviceMountImage;
    DVTRadarComponentKey = 487927;
    NSLocalizedFailure = "This operation can fail if the version of the OS on the device is newer than the version of Xcode that is running.";
}
--
Could not support development.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653066
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE8000076)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x0000000124eb799f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x0000000124ef3f98 -[DTDKMobileDeviceToken _mountDeveloperDiskImage:withError:] + 1024
	2   DTDeviceKitBase                     0x0000000124ef49b8 __58-[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:]_block_invoke + 609
	3   libdispatch.dylib                   0x00007fff201887c7 _dispatch_client_callout + 8
	4   libdispatch.dylib                   0x00007fff20195605 _dispatch_lane_barrier_sync_invoke_and_complete + 60
	5   DTDeviceKitBase                     0x0000000124ef46f5 -[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:] + 188
	6   IDEiOSSupportCore                   0x0000000124d48821 __37-[DVTiOSDevice(Connect) hasConnected]_block_invoke_2 + 258
	7   DVTFoundation                       0x00000001040022ae __DVT_CALLING_CLIENT_BLOCK__ + 7
	8   DVTFoundation                       0x00000001040070fb __DVTDispatchGroupAsync_block_invoke + 1191
	9   libdispatch.dylib                   0x00007fff201875dd _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x00007fff201887c7 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00007fff2018b20d _dispatch_continuation_pop + 543
	12  libdispatch.dylib                   0x00007fff2018a868 _dispatch_async_redirect_invoke + 713
	13  libdispatch.dylib                   0x00007fff20197857 _dispatch_root_queue_drain + 326
	14  libdispatch.dylib                   0x00007fff20197fb8 _dispatch_worker_thread2 + 92
	15  libsystem_pthread.dylib             0x00007fff20330453 _pthread_wqthread + 244
	16  libsystem_pthread.dylib             0x00007fff2032f467 start_wqthread + 15
);
}
--

System Information

macOS Version 11.0.1 (Build 20B50)
Xcode 12.2 (17535) (Build 12B45b)
Timestamp: 2020-12-02T12:13:09+01:00

</details>

**Comment by filsv** [comment]
@sstadtl Hi, try to use [14.3 support files](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/14.3.zip).
