### ISSUE TITLE
Developer disk image iOS 12.5 (16H20)

### ISSUE THREAD

**Issue by patelgaurav4u** [filsv/iPhoneOSDeviceSupport#79]

**Comment by filsv** [comment]
@patelgaurav4u hi, did you tried to rename [12.4 (16G73)](https://github.com/filsv/iPhoneOSDeviceSupport/blob/master/12.4%20(16G73).zip) files to "12.5 (16H20).zip"

**Comment by filsv** [comment]
@patelgaurav4u I'll close this issue, if you still have a problem please reopen it.
