### ISSUE TITLE
Support files for 14.4 (18D52)

### ISSUE THREAD

**Issue by murali129** [filsv/iPhoneOSDeviceSupport#83]
I am not able to run the app in the device because of no support to 14.4

**Comment by Bullseye25** [comment]
Same here

**Comment by mehdigriche** [comment]
same !

**Comment by irfansener** [comment]
Same :(

**Comment by abdulbasit4726** [comment]
same

**Comment by A-M-j** [comment]
try to duplicate file "14.3"  rename to "14.4"  it works well

**Comment by maykl4iv** [comment]
It doesn`t

**Comment by lucaslovato** [comment]
There's an open PR for 14.4. It worked for me.

**Comment by maykl4iv** [comment]
Thanks!

**Comment by filsv** [comment]
Hi guys, added 14.4, [Download link](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/14.4.zip).
@murali129 & @Bullseye25 & @mehdigriche & @irfansener & @abdulbasit4726 & @A-M-j & @maykl4iv & @lucaslovato

**Comment by maykl4iv** [comment]
Thanks!
