### ISSUE TITLE
ios 14.5.1 (18E212)

### ISSUE THREAD

**Issue by lgArlequin** [filsv/iPhoneOSDeviceSupport#90]
Hello, Are you scheduled to release the update for version 14.5.1?

**Comment by AshleyDeng** [comment]
@lgArlequin `iOS 14.5` package supports 14.5.1 as well

**Comment by k1er** [comment]
Xcode: 12.4  + iOS 14.5 package
iPhone 11 Pro iOS 14.5 
all variables is nil in debugger breakpoint ,has anyone encountered this problem?

**Comment by lgArlequin** [comment]
Sorry, it was my mistake, this package works for 14.5.1
