### ISSUE TITLE
iOS 14.6

### ISSUE THREAD

**Issue by Niko-by** [filsv/iPhoneOSDeviceSupport#91]
Please add support for iOS 14.6

**Comment by g-mocken** [comment]
After debugging a project on my iPad with iPadOS 14.6 just once with the most recent Xcode 12.5 (on BigSur), now my Xcode 12.4 (on Catalina) can also do it - even without specific iOS 14.6 device support files. Apparently, Xcode 12.5 installs the required files on the device itself?!
Please try and confirm (before I update my other devices).

**Comment by mrugeshtank** [comment]
Confirmed:

On mac OS 10.15.7 with Xcode 12.4 can not run or debug devices with iOS 14.6.

On mac OS 11.3.1 with Xcode 12.5 can run and debug as usual with iOS 14.6.

Also not finding 14.6 directory or files in Xcode 12.5's package.

**Comment by g-mocken** [comment]
Now please also try whether you can debug on 10.15.7/XC12.4 when you use the _same_ iOS 14.6. device that you _previously_ debugged successfully on 11.3.1/XC12.5 (without rebooting that device). Because that also miraculously works for me.
The setup survives a reboot of the Mac, but not a reboot of the iPad. But it seems to be reproducible.

**Comment by g-mocken** [comment]
There now is an even better [solution](https://github.com/iGhibli/iOS-DeviceSupport/issues/151#issuecomment-850387057).

**Comment by Niko-by** [comment]
There was a problem, all applications started and hung on the start screen. I went through xCode, built and launched the project there, only after that the projects began to run well through vs code. I don’t know what it’s connected with, maybe xCode downloads some support files at the first start

**Comment by pradeep7may** [comment]
I need support of 14.7  as I can't update to Big Sur. Can anyone add that support also.

**Comment by nikunj5294** [comment]
You can download iOS 14.6 device support file from here.

Cheers..!! 

[14.6.zip](https://github.com/filsv/iPhoneOSDeviceSupport/files/6669326/14.6.zip)

**Comment by filsv** [comment]
@Niko-by @g-mocken @pradeep7may Here is iOS 14.6 support files, [download](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/14.6.zip).

Thanks to @nikunj5294
