### ISSUE TITLE
IOS 12.5.3

### ISSUE THREAD

**Issue by TeamRainless** [filsv/iPhoneOSDeviceSupport#94]
Can we please have the support files for IOS 12.5?

**Comment by filsv** [comment]
@TeamRainless Hi, have you tried to use iOS 13.0 support files instead? You sure that you need specifically iOS 12.5.3?

**Comment by TeamRainless** [comment]
@filsv you are correct! I had tried 12 and I'd tried 14 but I hadn't tried 13. 13 works perfectly.  This was on an iPad mini 2.
