### ISSUE TITLE
14.7 device support files are missing

### ISSUE THREAD

**Issue by krishtoautomate** [filsv/iPhoneOSDeviceSupport#95]
can you please add 14.7 device support files. thanks

**Comment by Lailan** [comment]
As a workaround in the meantime, I was able to deploy apps using Xcode 12.4 (12D4e) to an iPhone running iOS 14.7 by copying the iOS 14.6 device support files and placing them in a folder named iOS 14.7. Navigate to /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/, copy the 14.6 folder, and rename it 14.7. Be sure to restart Xcode afterwards. You can verify whether this worked by checking your device's status in the Window > Devices and Simulators menu.

Hope this helps.

**Comment by magic3584** [comment]
@Lailan 
Is there a situation that Xcode lost device connection after a breakpoint?

**Comment by filsv** [comment]
@Lailan Thanks! @krishtoautomate have you fixed an issue?

**Comment by krishtoautomate** [comment]
no not fixed and I updated to ios 15

**Comment by nikunj5294** [comment]
Does anyone found 14.7 device support?

**Comment by filsv** [comment]
@krishtoautomate @nikunj5294 
Yo guys, [here 14.7](https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/14.7.zip).

**Comment by nikunj5294** [comment]
Thanks..!! @filsv
