### ISSUE TITLE
14.7 device support files are missing

### ISSUE THREAD

**Issue by smartgeekscol** [filsv/iPhoneOSDeviceSupport#96]
please add this file

**Comment by Lailan** [comment]
As a workaround in the meantime, I was able to deploy apps using Xcode 12.4 (12D4e) to an iPhone running iOS 14.7 by copying the iOS 14.6 device support files and placing them in a folder named iOS 14.7. Navigate to /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/, copy the 14.6 folder, and rename it 14.7. Be sure to restart Xcode afterwards. You can verify whether this worked by checking your device's status in the Window > Devices and Simulators menu.

Hope this helps.

**Comment by smartgeekscol** [comment]
Thanks friend, it worked
